# @package _global_

defaults:
  - override /dataset: copa
  - override /model: mbert
  - override /madx: madx
  - override /params: params
  - override /trainer: trainer

madx:
  lang_adapter:
    en: en/wiki@ukp
    et: et/wiki@ukp
    ht: ht/wiki@ukp
    id: id/wiki@ukp
    qu: qu/wiki@ukp
    sw: sw/wiki@ukp
    tr: tr/wiki@ukp
    vi: vi/wiki@ukp
    zh: zh/wiki@ukp
  task_adapter:
    name: copa
model:
  num_labels: 2
  batch_size: 8
params:
  max_epochs: 2
trainer:
  devices: 1