# @package _global_

defaults:
  - override /dataset: copa
  - override /madx: madx
  - override /model: xlmr
  - override /params: params
  - override /trainer: trainer

madx:
  task_adapter:
    name: copa
model:
  num_labels: 2
params:
  max_epochs: 2
  batch_size: 24
trainer:
  devices: 1