# @package _global_

defaults:
- override /dataset: xxstorycloze
- override /madx: null
- override /model: xlmr
- override /params: params
- override /trainer: trainer

model:
  num_labels: 2
params:
  batch_size: 6
  max_epochs: 2
trainer:
  
