# @package _global_

defaults:
  - override /dataset: copa
  - override /madx: null
  - override /model: xlmr
  - override /params: params
  - override /trainer: trainer

model:
  num_labels: 2
params:
  lr: 2e-5
  weight_decay: 0.05
  decay: 0.1
trainer:
  exp_name: copa_xlmr_fft
  max_epochs: 10
  every_n_epochs: 1
  save_top_k: 1