# @package _global_

defaults:
  - override /dataset:
    - balanced_copa
    - social_i_qa
  - override /madx: null
  - override /model: xlmr
  - override /params: params
  - override /trainer: trainer

model:
  num_labels: 2
params:
  lr: 2e-5
trainer:
  exp_name: copa_xlmr_fft