# @package _global_

defaults:
  - override /dataset: copa
  - override /madx: madx
  - override /model: xlmr
  - override /params: params
  - override /trainer: trainer
 
madx:
  task_adapter:
    name: copa
model:
  num_labels: 2
  batch_size: 24
params:
  lr: 1e-4
trainer:
  devices:
    darwin: auto
    linux: 1
  exp_name: copa_xlmr_ta
