# @package _global_

defaults:
  - override /dataset: copa
  - override /madx: madx
  - override /model: xlmr
  - override /params: params
  - override /trainer: trainer
 
madx:
  lang_adapter:
    et: et/wiki@ukp
    ht: ht/wiki@ukp
    id: id/wiki@ukp
    qu: qu/wiki@ukp
    sw: sw/wiki@ukp
    tr: tr/wiki@ukp
    vi: vi/wiki@ukp
    zh: zh/wiki@ukp
  task_adapter:
    name: copa
model:
  num_labels: 2
  batch_size: 24
params:
  lr: 1e-4
trainer:
  devices:
    darwin: auto
    linux: 1
  exp_name: copa_xlmr_madx
