# @package _global_

defaults:
  - override /dataset: copa
  - override /madx: null
  - override /params: params
  - override /trainer: trainer

model:
  num_labels: 2
params:
  lr: 2e-5
trainer:
  exp_name: copa_mbert_fft