# @package _global_

defaults:
  - override /dataset: copa
  - override /madx: madx
  - override /model: xlmr
  - override /params: params
  - override /trainer: trainer
 
madx:
  task_adapter:
    name: copa
model:
  num_labels: 2
params:
  batch_size: 6
  lr: 1e-4
  label_smoothing: 0.1
trainer:
  exp_name: copa_xlmr_ta_ls
