# @package _global_

defaults:
  - override /dataset: copa
  - override /model: mbert
  - override /madx: madx
  - override /params: params
  - override /trainer: trainer

madx:
  task_adapter:
    name: copa
model:
  num_labels: 2
params:
  batch_size: 6
  lr: 1e-4
trainer:
  exp_name: copa_mbert_ta