# @package _global_

defaults:
  - override /dataset:
    - paws_x
  - override /madx: null
  - override /model: mbert
  - override /params: params
  - override /trainer: trainer

model:
  num_labels: 2
params:
  lr: 2e-5
  weight_decay: 0.05
  warmup: 0.1
trainer:
  exp_name: paws_x_mbert_fft
  max_epochs: 10