# @package _global_

defaults:
  - override /dataset:
    - balanced_copa
    - social_i_qa
  - override /model: mbert
  - override /madx: madx
  - override /params: params
  - override /trainer: trainer

madx:
    task_adapter:
      name: copa
model:
  num_labels: 2
params:
  lr: 1e-4
trainer:
  exp_name: xcopa_mbert_madx