# @package _global_

defaults:
  - override /dataset:
    - balanced_copa
    - social_i_qa
  - override /madx: madx
  - override /model: xlmr
  - override /params: params
  - override /trainer: trainer
 
dataset:
  balanced_copa:
    train_split: train
    val_split: test
  social_i_qa:
    train_split: train
    val_split: validation
madx:
    task_adapter:
      name: copa
model:
  num_labels: 2
params:
  lr: 1e-4
trainer:
  exp_name: xcopa_xlmr_madx
