# @package _global_

defaults:
- override /madx: null
- override /model: xlmr
- override /params: params
- override /trainer: trainer

params:
  lr: 2e-5
  label_smoothing: 0.1
trainer:
  exp_name: xnli_xlmr_fft_ls
  