# @package _global_

defaults:
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer

madx:
  lang_adapter:
    ar: ar/wiki@ukp
    de: de/wiki@ukp
    en: en/wiki@ukp
    es: es/wiki@ukp
    hi: hi/wiki@ukp
    ru: ru/wiki@ukp
    sw: sw/wiki@ukp
    tr: tr/wiki@ukp
    vi: vi/wiki@ukp
    zh: zh/wiki@ukp
params:
  lr: 1e-4
  label_smoothing: 0.1
trainer:
  exp_name: xnli_xlmr_tala_ls