defaults:
  - _self_
  - dataset:
    - xnli
  - lora: null
  - madx: madx
  - model: mbert
  - params: params
  - trainer: trainer
  - wandb: wandb
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

project: master-thesis
work_dir: ${hydra:runtime.cwd}

# path to folder to model checkpoints
data_dir:
  Darwin: "data"
  Linux: "/ceph/mgaber/data"