defaults:
  - _self_
  - dataset:
    - xnli.yaml
  - lora: null
  - madx: madx.yaml
  - model: mbert.yaml
  - params: params.yaml
  - wandb: wandb.yaml
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

project: master-thesis
work_dir: ${hydra:runtime.cwd}

# path to folder to model checkpoints
data_dir_mac: data
data_dir_linux: ../../../ceph/mgaber/data