# @package _global_

defaults:
  - adapter/lang_adapter: null
  - adapter/task_adapter: mnli.yaml
  - dataset:
    - xnli.yaml
  - experiment: xcopa_mbert.yaml
  - model: mbert.yaml
  - params: params.yaml

project: "master-thesis"