defaults:
  - _self_
  - dataset:
    - xnli.yaml
  - experiment: null
  - lora: null
  - madx: madx.yaml
  - model: mbert.yaml
  - params: params.yaml
  - wandb: wandb.yaml
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

project: master-thesis
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/
# path to folder to model checkpoints
checkpoint_dir: ${work_dir}/data/checkpoints/