# @package _global_

defaults:
- override /dataset: paws_x
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer

madx:
  lang_adapter:
    de: de/wiki@ukp
    en: en/wiki@ukp
    es: es/wiki@ukp
    ja: ja/wiki@ukp
    zh: zh/wiki@ukp
  task_adapter:
    name: paws-x
model:
  num_labels: 2
params:
  lr: 1e-4
  label_smoothing: 0.1
trainer:
  exp_name: paws_x_xlmr_tala_ls
