# @package _global_

defaults:
- override /dataset: paws_x
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer

madx:
  task_adapter:
    name: paws-x
model:
  num_labels: 2
params:
  lr: 1e-4
trainer:
  exp_name: paws_x_xlmr_ta
