# @package _global_

defaults:
- override /dataset: xcopa
- override /model: mbert
- override /madx: madx
- override /params: params
- override /trainer: trainer

madx:
  lang_adapter:
    en: en/wiki@ukp
    et: et/wiki@ukp
    ht: ht/wiki@ukp
    id: id/wiki@ukp
    qu: qu/wiki@ukp
    sw: sw/wiki@ukp
    tr: tr/wiki@ukp
    vi: vi/wiki@ukp
    zh: zh/wiki@ukp
  task_adapter:
    name: xcopa
model:
  num_labels: 2
params:
  batch_size: 6
  lr: 1e-4
trainer:
  exp_name: xcopa_mbert_tala
