# @package _global_

defaults:
- override /dataset: xcopa
- override /madx: null
- override /model: xlmr
- override /params: params
- override /trainer: trainer

model:  
  num_labels: 2
params:
  batch_size: 8
  label_smoothing: 0.1
  lr: 2e-5
trainer:
  exp_name: xcopa_xlmr_fft_ls
