# @package _global_

defaults:
- override /dataset: xstorycloze
- override /madx: null
- override /model: xlmr
- override /params: params
- override /trainer: trainer

model:
  num_labels: 2
params:
  batch_size: 6
  lr: 2e-5
trainer:
  exp_name: xsc_xlmr_fft
