# @package _global_

defaults:
- override /dataset: xstorycloze
- override /madx: null
- override /params: params
- override /trainer: trainer

model:
  num_labels: 2
params:
  batch_size: 6
  label_smoothing: 0.1
  lr: 2e-5
trainer:
  exp_name: xstorycloze_mbert_fft_ls
