# @package _global_

defaults:
- override /dataset: xstorycloze
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer

madx:
  task_adapter:
    name: xstorycloze
model:
  num_labels: 2
params:
  batch_size: 6
  label_smoothing: 0.1
  lr: 1e-4
trainer:
  exp_name: xstorycloze_xlmr_ta_ls
