# @package _global_
defaults:
- override /dataset: paws_x
- override /madx: null
- override /model: xlmr
- override /params: params
- override /trainer: trainer
dataset:
  target_lang: [de, es, fr, ja, zh]
model:
  ckpt_avg: none
  ckpt_dir: mixup_en_ko_paws_x_xlmr_fft
  num_labels: 2
params:
  lr: 2e-5
  source_lang: [en, ko]
trainer:
  exp_name: mixup_en_ko_paws_x_xlmr_fft