# @package _global_
defaults:
- override /dataset: paws_x
- override /madx: null
- override /model: mbert
- override /params: params
- override /trainer: trainer
dataset:
  target_lang: [de, fr, ja, ko, zh]
model:
  ckpt_avg: none
  ckpt_dir: mixup_en_es_paws_x_mbert_fft
  num_labels: 2
params:
  lr: 2e-5
  source_lang: [en, es]
trainer:
  exp_name: mixup_en_es_paws_x_mbert_fft