# @package _global_
defaults:
- override /dataset: paws_x
- override /madx: null
- override /model: xlmr
- override /params: params
- override /trainer: trainer
dataset:
  target_lang: [de, en, es, fr, ja, ko, zh]
model:
  ckpt_avg: none
  ckpt_dir: mslt_en_de_paws_x_xlmr_fft
  num_labels: 2
params:
  lr: 2e-5
  source_lang: [en, de]
trainer:
  exp_name: mslt_en_de_paws_x_xlmr_fft