# @package _global_
defaults:
- override /dataset: paws_x
- override /madx: madx
- override /model: xlmr
- override /trainer: trainer
- override /params: params
madx:
  lang_adapter:
    de: de/wiki@ukp
    en: en/wiki@ukp
    es: es/wiki@ukp
    ja: ja/wiki@ukp
    zh: zh/wiki@ukp
  task_adapter:
    name: paws-x
model:
  ca_strategy: last
  ckpt_dir: paws_x_xlmr_tala_ls
  num_labels: 2
params:
  label_smoothing: 0.1
  lr: 1e-4
trainer:
  exp_name: paws_x_xlmr_tala_ls_last
