# @package _global_
defaults:
- override /dataset: paws_x
- override /madx: null
- override /model: mbert
- override /trainer: trainer
- override /params: params
model:
  ca_strategy: best
  ckpt_dir: paws_x_mbert_fft_ls
  num_labels: 2
params:
  label_smoothing: 0.1
  lr: 2e-5
trainer:
  exp_name: paws_x_mbert_fft_ls_best
