# @package _global_
defaults:
- override /dataset: paws_x
- override /madx: null
- override /model: mbert
- override /trainer: trainer
- override /params: params
model:
  ca_strategy: best
  ckpt_dir: paws_x_mbert_fft
  num_labels: 2
params:
  lr: 2e-5
trainer:
  exp_name: paws_x_mbert_fft_oob_best
