# @package _global_
defaults:
- override /madx: null
- override /model: xlmr
- override /trainer: trainer
- override /params: params
model:
  ca_strategy: last
  ckpt_dir: schmidt_xnli_xlmr_fft
  ckpts_to_load: 10
params:
  lr: 2e-5
trainer:
  exp_name: schmidt_xnli_xlmr_fft_oob_last
  max_epochs: 10