# @package _global_
defaults:
- override /dataset: xcopa
- override /madx: null
- override /model: xlmr
- override /params: params
- override /trainer: trainer
- override /params: params
model:
  ca_strategy: best
  ckpt_dir: xcopa_xlmr_fft
  num_labels: 2
params:
  batch_size: 8
trainer:
  exp_name: xcopa_xlmr_fft_oob_best
