# @package _global_
defaults:
- override /dataset: xcopa
- override /madx: madx
- override /params: params
- override /trainer: trainer
- override /params: params
madx:
  task_adapter:
    name: xcopa
model:
  ca_strategy: best
  ckpt_dir: xcopa_mbert_ta_ls
  num_labels: 2
params:
  batch_size: 8
trainer:
  exp_name: xcopa_mbert_ta_ls_best
