# @package _global_
defaults:
- override /dataset: xcopa
- override /madx: null
- override /params: params
- override /trainer: trainer
- override /params: params
model:
  ckpt_avg: none
  ckpt_dir: xcopa_mbert_fft_ls
  num_labels: 2
params:
  batch_size: 8
trainer:
  exp_name: xcopa_mbert_fft_ls_none
