# @package _global_
defaults:
- override /madx: null
- override /model: mbert
- override /trainer: trainer
- override /params: params
model:
  ckpt_avg: best
  ckpt_dir: xnli_mbert_fft_ls
params:
  label_smoothing: 0.1
  lr: 2e-5
trainer:
  exp_name: xnli_mbert_fft_ls_best
