# @package _global_
defaults:
- override /madx: null
- override /model: mbert
- override /trainer: trainer
- override /params: params
model:
  ca_strategy: last
  ckpt_dir: xnli_mbert_fft
params:
  lr: 2e-5
trainer:
  exp_name: xnli_mbert_fft_oob_last
