# @package _global_
defaults:
- override /model: xlmr
- override /trainer: trainer
- override /params: params
model:
  ckpt_avg: none
  ckpt_dir: xnli_xlmr_ta_ls
params:
  label_smoothing: 0.1
  lr: 1e-4
trainer:
  exp_name: xnli_xlmr_ta_ls_none
