# @package _global_
defaults:
- override /madx: null
- override /model: xlmr
- override /trainer: trainer
- override /params: params
model:
  ckpt_avg: none
  ckpt_dir: xnli_xlmr_fft
params:
  lr: 2e-5
trainer:
  exp_name: xnli_xlmr_fft_oob_none
