# @package _global_
defaults:
- override /model: mbert
- override /trainer: trainer
- override /params: params
model:
  ca_strategy: last
  ckpt_dir: xnli_mbert_ta_ls
params:
  label_smoothing: 0.1
  lr: 1e-4
trainer:
  exp_name: xnli_mbert_ta_ls_last
