# @package _global_
defaults:
- override /madx: madx
- override /model: mbert
- override /trainer: trainer
- override /params: params
madx:
  lang_adapter:
    ar: ar/wiki@ukp
    de: de/wiki@ukp
    el: el/wiki@ukp
    en: en/wiki@ukp
    es: es/wiki@ukp
    hi: hi/wiki@ukp
    ru: ru/wiki@ukp
    sw: sw/wiki@ukp
    tr: tr/wiki@ukp
    vi: vi/wiki@ukp
    zh: zh/wiki@ukp
model:
  ca_strategy: none
  ckpt_dir: xnli_mbert_tala
params:
  temp_scaling: true
trainer:
  exp_name: xnli_mbert_tala_ts_none
