# @package _global_
defaults:
- override /madx: null
- override /model: xlmr
- override /trainer: trainer
- override /params: params
model:
  ca_strategy: none
  ckpt_dir: xnli_xlmr_fft
params:
  temp_scaling: true
trainer:
  exp_name: xnli_xlmr_fft_ts_none
