# @package _global_
defaults:
- override /dataset: xstorycloze
- override /madx: madx
- override /params: params
- override /trainer: trainer
- override /params: params
madx:
  lang_adapter:
    ar: ar/wiki@ukp
    en: en/wiki@ukp
    es: es/wiki@ukp
    hi: hi/wiki@ukp
    id: id/wiki@ukp
    my: my/wiki@ukp
    ru: ru/wiki@ukp
    sw: sw/wiki@ukp
    zh: zh/wiki@ukp
  task_adapter:
    name: xstorycloze
model:
  ckpt_avg: last
  ckpt_dir: xsc_mbert_tala_ls
  num_labels: 2
params:
  batch_size: 6
trainer:
  exp_name: xsc_mbert_tala_ls_last
