# @package _global_
defaults:
- override /dataset: xstorycloze
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer
- override /params: params
madx:
  task_adapter:
    name: xstorycloze
model:
  ca_strategy: last
  ckpt_dir: xsc_xlmr_ta
  num_labels: 2
params:
  batch_size: 6
  temp_scaling: true
trainer:
  exp_name: xsc_xlmr_ta_ts_last
