defaults:
- _self_
- dataset: xnli
- lora: null
- madx: madx
- model: mbert
- params: params
- trainer: trainer
- wandb: wandb
- override hydra/hydra_logging: colorlog
- override hydra/job_logging: colorlog

# path to folder where datasets and checkpoints will be stored
data_dir: "/ceph/mgaber/data"