num_epochs: 2
batch_size: 32
optimizer: AdamW
lr: 5e-5
val_metric: accuracy
uncertainty_metric: expected_calibration_error
average: micro
source_lang: en
seed: 42
max_epochs: 5
label_smoothing: 0
devices: 2