num_epochs: 2
batch_size: 32
optimizer: adamW
lr: 5e-5
warmup_ratio: 0.05
pred_metric: accuracy
uncert_metric: ece # expected calibration error
average: micro
source_lang: en
seed: [0, 1, 2, 3, 4]
label_smoothing: 0