# @package _global_
defaults:
- override /dataset: paws_x
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer
madx:
  task_adapter:
    name: paws-x
model:
  num_labels: 2
params:
  max_epochs: 2
trainer:
  exp_name: sweep_paws_x_xlmr_ta
  save_top_k: 0
