# @package _global_
defaults:
- override /dataset: xcopa
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer
madx:
  task_adapter:
    name: xcopa
model:  
  num_labels: 2
params:
  batch_size: 8
  max_epochs: 2
trainer:
  exp_name: sweep_xcopa_xlmr_ta
  save_top_k: 0
  
