# @package _global_
defaults:
- override /dataset: xsc
- override /madx: null
- override /params: params
- override /trainer: trainer
model:
  num_labels: 2
params:
  batch_size: 6
  max_epochs: 2
trainer:
  exp_name: sweep_xsc_mbert_fft
  save_top_k: 0
  
