# @package _global_

defaults:
- override /dataset: paws_x paws_x
- override /madx: madx
- override /model: mbert
- override /params: params

madx:
  task_adapter:
    name: paws-x
model:
  num_labels: 2
params:
  max_epochs: 2

