# @package _global_

defaults:
- override /dataset: paws_x
    
- override /madx: null
- override /model: xlmr
- override /params: params
  
dataset:
  paws_x:
    train_split: train
    val_split: validation
    test_split: validation
model:
  num_labels: 2
params:
  max_epochs: 2