# @package _global_

defaults:
- override /dataset: xcopa
- override /model: mbert
- override /madx: madx
- override /params: params
- override /trainer: trainer

madx:
  task_adapter:
    name: xcopa
model:
  batch_size: 8  
  num_labels: 2
params:
  max_epochs: 2
trainer:
  
