# @package _global_

defaults:
- override /dataset: xxstorycloze
- override /madx: madx
- override /model: xlmr
- override /params: params
- override /trainer: trainer

madx:
  task_adapter:
    name: xstorycloze
model:  
  num_labels: 2
params:
  batch_size: 6
  max_epochs: 2
trainer:
  
