# @package _global_

defaults:
- override /dataset: xxstorycloze
- override /model: mbert
- override /madx: madx
- override /params: params
- override /trainer: trainer

madx:
  lang_adapter:
    en: en/wiki@ukp
    et: et/wiki@ukp
    ht: ht/wiki@ukp
    id: id/wiki@ukp
    qu: qu/wiki@ukp
    sw: sw/wiki@ukp
    tr: tr/wiki@ukp
    vi: vi/wiki@ukp
    zh: zh/wiki@ukp
  task_adapter:
    name: xxstorycloze
model:
  batch_size: 6
  num_labels: 2
params:
  max_epochs: 2
trainer:
  
