max_epochs: 5
gpu_name:
  darwin: mps:0 # Mac GPU
  linux: cuda
devices:
  darwin: auto
  linux: 2
strategy:
  darwin: auto
  linux: ddp
map_location:
  darwin: mps
  linux: cuda
save_top_k: -1
exp_name: xnli_mbert_madx